[build]
command = "npm install"

[deploy]
command = "node functions/efipay-proxy.js"

[services]
  [services.efipay-proxy]
  internal_port = 8080
  protocol = "http"
  auto_start = true
  auto_stop = true
